# Generated by Django 4.0.5 on 2022-06-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AVScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_title', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('SAFE', 'Safe'), ('MALICIOUS', 'Malicious')], default='PENDING', max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='avscanstatus',
            index=models.Index(fields=['content_type', 'object_id'], name='home_avscan_content_309c8c_idx'),
        ),
    ]
